"use client";

import { useState } from "react";
import { dimensionLabel, type TraceStep } from "@/lib/emotion";

/**
 * Full transparency view: every calculation step the engine took, with a
 * plain-English explanation of WHAT the step does, the engine's own
 * narration, and the raw numbers it produced. The final step shows the
 * per-dimension composition (how much each layer contributed) — the heart
 * of "show me how you got this number".
 */

// What each step means, in plain language. Keyed by step number.
const STEP_EXPLAIN: Record<number, string> = {
  1: "Your lifelong emotional baseline, read from the natal Moon — its sign (30%), nakshatra (40%), the house it occupies (20%), and any planet sitting close to it (10%). This barely changes over a lifetime.",
  2: "The current life-season. Your active Dasha / Bhukti / Antara lords each contribute their emotional nature, weighted 50 / 30 / 20. If a lord is also today's nakshatra lord (Step 5) or the transit Moon is touching its natal position (Step 8), its influence is amplified.",
  3: "Today's emotional trigger — where the Moon is right now. Its sign and nakshatra add a gentle daily colour (scaled down, because the day nudges rather than defines).",
  4: "Which area of life today's Moon activates, counted as a house from your natal Moon. The 6th leans toward stress, the 8th toward sensitivity, the 11th toward connection, and so on.",
  6: "Tara Bala — the 9-fold 'star strength' between your birth nakshatra and today's. Some taras (Sampat, Sadhaka) are supportive; others (Vipat, Naidhana) are draining.",
  7: "Chandra Ashtama — the Moon transiting the 8th from your natal Moon. A classically low-energy, inward day. When active, it adds stress and sensitivity and dampens confidence.",
  9: "Every dimension starts at a neutral 50, then each layer's contribution is added (natal 30% + DBA 40% + transit 30%, with a gain so strong factors swing the score). The breakdown below shows exactly how much each layer moved each dimension.",
  10: "Plain-language reading, generated by threshold rules on the final scores (e.g. confidence above 80 → a leadership day).",
};

export function EmotionTrace({ trace }: { trace: TraceStep[] }) {
  return (
    <div className="flex flex-col gap-2">
      {trace.map((s) => (
        <TraceRow key={s.step} step={s} />
      ))}
    </div>
  );
}

function TraceRow({ step }: { step: TraceStep }) {
  const [open, setOpen] = useState(false);
  const explain = STEP_EXPLAIN[step.step];

  return (
    <div className="rounded-lg border border-[var(--border-glass)] bg-[rgba(15,17,35,0.5)]">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        className="flex w-full items-start gap-3 p-3 text-left"
      >
        <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-[var(--border-strong)] text-xs text-[var(--accent-gold)]">
          {step.step}
        </span>
        <span className="flex-1">
          <span className="block text-sm font-medium text-[var(--text-main)]">{step.title}</span>
          <span className="mt-0.5 block text-xs leading-relaxed text-[var(--text-muted)]">
            {step.narration}
          </span>
        </span>
        <span className="mt-1 shrink-0 text-xs text-[var(--text-muted)]">{open ? "−" : "+"}</span>
      </button>

      {open && (
        <div className="border-t border-[var(--border-glass)] p-3 text-xs">
          {explain && (
            <p className="mb-3 rounded-md bg-[rgba(139,92,246,0.08)] p-2 leading-relaxed text-[var(--text-muted)]">
              <span className="font-medium text-[var(--accent-purple)]">What this does — </span>
              {explain}
            </p>
          )}
          <StepData step={step} />
        </div>
      )}
    </div>
  );
}

// Renders the step's data in the most legible shape per step.
function StepData({ step }: { step: TraceStep }) {
  const d = step.data;

  if (step.step === 2 && Array.isArray(d.breakdown)) {
    return <DbaBreakdown breakdown={d.breakdown as DbaLevel[]} />;
  }
  if (step.step === 9 && d.composition && typeof d.composition === "object") {
    return (
      <CompositionTable
        composition={d.composition as Record<string, Composition>}
        gain={typeof d.intensity_gain === "number" ? d.intensity_gain : undefined}
      />
    );
  }
  // Generic: render any {dimension: number} delta maps as chips, else JSON.
  return <GenericData data={d} />;
}

type DbaLevel = {
  level: string;
  lord: string;
  subweight: number;
  multiplier: number;
  vector: Record<string, number | string>;
  notes: string[];
};

function DbaBreakdown({ breakdown }: { breakdown: DbaLevel[] }) {
  return (
    <div className="flex flex-col gap-2">
      {breakdown.map((b) => (
        <div key={b.level} className="rounded-md border border-[var(--border-glass)] p-2">
          <div className="flex items-center justify-between">
            <span className="text-[var(--text-main)]">
              <span className="uppercase tracking-wide text-[var(--text-muted)]">{b.level}</span>{" "}
              · <strong>{b.lord}</strong>
            </span>
            <span className="text-[var(--text-muted)]">
              weight {b.subweight} {b.multiplier !== 1 && <span className="text-[var(--accent-gold)]">× {b.multiplier}</span>}
            </span>
          </div>
          <DeltaChips data={b.vector} />
          {b.notes?.length > 0 && (
            <div className="mt-1 text-[0.7rem] italic text-[var(--accent-gold)]">
              {b.notes.join(" · ")}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

type Composition = { natal: number; dba: number; transit: number; raw: number };

function CompositionTable({
  composition,
  gain,
}: {
  composition: Record<string, Composition>;
  gain?: number;
}) {
  return (
    <div>
      {gain !== undefined && (
        <p className="mb-2 text-[var(--text-muted)]">
          Formula: <code>score = 50 + {gain} × (0.30·natal + 0.40·dba + 0.30·transit)</code>, clamped 0–100.
        </p>
      )}
      <div className="overflow-x-auto">
        <table className="w-full border-collapse text-[0.7rem]">
          <thead>
            <tr className="text-[var(--text-muted)]">
              <th className="px-2 py-1 text-left font-normal">Dimension</th>
              <th className="px-2 py-1 text-right font-normal">Natal</th>
              <th className="px-2 py-1 text-right font-normal">DBA</th>
              <th className="px-2 py-1 text-right font-normal">Transit</th>
              <th className="px-2 py-1 text-right font-normal">Score</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(composition).map(([dim, c]) => (
              <tr key={dim} className="border-t border-[var(--border-glass)]">
                <td className="px-2 py-1 text-[var(--text-main)]">{dimensionLabel(dim)}</td>
                <Cell v={c.natal} />
                <Cell v={c.dba} />
                <Cell v={c.transit} />
                <td className="px-2 py-1 text-right font-semibold tabular-nums text-[var(--accent-gold)]">
                  {Math.max(0, Math.min(100, Math.round(c.raw)))}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function Cell({ v }: { v: number }) {
  const color =
    v > 0 ? "#86efac" : v < 0 ? "#f5a97f" : "var(--text-muted)";
  return (
    <td className="px-2 py-1 text-right tabular-nums" style={{ color }}>
      {v > 0 ? "+" : ""}
      {v}
    </td>
  );
}

function DeltaChips({ data }: { data: Record<string, number | string> }) {
  const entries = Object.entries(data).filter(([k]) => !k.startsWith("_"));
  if (entries.length === 0) return null;
  return (
    <div className="mt-1 flex flex-wrap gap-1.5">
      {entries.map(([k, v]) => {
        const num = typeof v === "number" ? v : null;
        const color = num === null ? "var(--text-muted)" : num >= 0 ? "#86efac" : "#f5a97f";
        return (
          <span
            key={k}
            className="rounded-full border border-[var(--border-glass)] px-2 py-[1px] text-[0.7rem]"
            style={{ color }}
          >
            {dimensionLabel(k)} {num !== null && num >= 0 ? "+" : ""}
            {String(v)}
          </span>
        );
      })}
    </div>
  );
}

// Fallback renderer: pull out any nested {dimension: number} maps as chips,
// show scalars as key/value, and anything else as compact JSON.
function GenericData({ data }: { data: Record<string, unknown> }) {
  const entries = Object.entries(data).filter(([k]) => !k.startsWith("_"));
  return (
    <div className="flex flex-col gap-2">
      {entries.map(([k, v]) => {
        if (v && typeof v === "object" && !Array.isArray(v)) {
          const obj = v as Record<string, unknown>;
          const allNums = Object.values(obj).every((x) => typeof x === "number");
          if (allNums && Object.keys(obj).length > 0) {
            return (
              <div key={k}>
                <div className="text-[var(--text-muted)]">{prettyKey(k)}</div>
                <DeltaChips data={obj as Record<string, number>} />
              </div>
            );
          }
        }
        if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") {
          return (
            <div key={k} className="text-[var(--text-muted)]">
              {prettyKey(k)}: <span className="text-[var(--text-main)]">{String(v)}</span>
            </div>
          );
        }
        return (
          <details key={k}>
            <summary className="cursor-pointer text-[var(--text-muted)]">{prettyKey(k)}</summary>
            <pre className="mt-1 overflow-x-auto rounded bg-[rgba(0,0,0,0.35)] p-2 text-[0.65rem] leading-snug text-[var(--text-main)]">
              {JSON.stringify(v, null, 2)}
            </pre>
          </details>
        );
      })}
    </div>
  );
}

function prettyKey(k: string): string {
  return k.replace(/_/g, " ").replace(/^\w/, (c) => c.toUpperCase());
}
